apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns
  labels: { name: frontend-ns }
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-ns
  labels: { name: backend-ns }
---
apiVersion: v1
kind: Namespace
metadata:
  name: db-storage-ns
  labels: { name: db-storage-ns }
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db-storage-ns
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-ns
data:
  DB_URL: "db-service.db-storage-ns.svc.cluster.local"